work_dir: ./work_dir/

# feeder
feeder: feeder.Feeder
train_feeder_args:
  mode: train
  data_path: ./data/train_images.npy
  label_path: ./data/train_masks.npy
test_feeder_args:
  mode: test
  data_path: ./data/test_images.npy
  label_path: ./data/test_masks.npy

# model
model: net.self_net
model_args:
  num_class: 4
  channel: 3

#optim
weight_decay: 1e-4
base_lr: 1e-2
step: [10, 50]

# training
device: 0
batch_size: 64 
test_batch_size: 64
num_epoch: 80
nesterov: True